import {
  getUserByEmailQuery,
  AddCohortQuery,
  createUserQuery,
  createUserRoleQuery,
  getCohortByNameQuery,
  getUserRoles,
  getPublicPostsQuery,
  getCohortPostsQuery,
  getCohortIdByNameQuery,
  addPostQuery,
  editPostQuery,
  deletePostQuery,
  getPostByIdQuery,
  getCountPostsQuery,
  getSingleCohortQuery,
  getAllCohortsQuery,
} from './query';

export {
  getUserByEmailQuery,
  getUserRoles,
  AddCohortQuery,
  createUserQuery,
  createUserRoleQuery,
  getCohortByNameQuery,
  getPublicPostsQuery,
  getCohortPostsQuery,
  getCohortIdByNameQuery,
  addPostQuery,
  editPostQuery,
  deletePostQuery,
  getPostByIdQuery,
  getCountPostsQuery,
  getSingleCohortQuery,
  getAllCohortsQuery,
};
