import {
  getUserByEmailQuery,
  AddCohortQuery,
  createUserQuery,
  createUserRoleQuery,
  getCohortByNameQuery,
  getUserRoles,
  getPublicPostsQuery,
  getCohortPostsQuery,
  getCohortIdByNameQuery,
  addPostQuery,
  editPostQuery,
  deletePostQuery,
  getPostByIdQuery,
  addLikeQuery,
  unlikeLikeQuery,
  checkQuery,
} from './query';

export {
  getUserByEmailQuery,
  getUserRoles,
  AddCohortQuery,
  createUserQuery,
  createUserRoleQuery,
  getCohortByNameQuery,
  getPublicPostsQuery,
  getCohortPostsQuery,
  getCohortIdByNameQuery,
  addPostQuery,
  editPostQuery,
  deletePostQuery,
  getPostByIdQuery,
  addLikeQuery,
  unlikeLikeQuery,
  checkQuery,
};
